AWSTemplateFormatVersion: 2010-09-09
Description: Dual VPC IPSec lab with inline dynamic config (Helm-like values)..

Mappings:
  Values:
    Config:
      VPCAName: "ipsec-vpc-lab"
      VPCBName: "ipsec-customer-lab"

      VPCA_CIDR: "10.0.0.0/16"
      VPCB_CIDR: "192.168.0.0/16"

      VPCA_EnableDnsHostnames: true
      VPCA_EnableDnsSupport: true
      VPCB_EnableDnsHostnames: false
      VPCB_EnableDnsSupport: true

      DefaultTenancy: "default"

Resources:
  VPCA:
    Type: AWS::EC2::VPC
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      CidrBlock: !FindInMap [Values, Config, VPCA_CIDR]
      EnableDnsSupport: !FindInMap [Values, Config, VPCA_EnableDnsSupport]
      EnableDnsHostnames: !FindInMap [Values, Config, VPCA_EnableDnsHostnames]
      InstanceTenancy: !FindInMap [Values, Config, DefaultTenancy]
      Tags:
        - Key: Name
          Value: !FindInMap [Values, Config, VPCAName]

  VPCB:
    Type: AWS::EC2::VPC
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      CidrBlock: !FindInMap [Values, Config, VPCB_CIDR]
      EnableDnsSupport: !FindInMap [Values, Config, VPCB_EnableDnsSupport]
      EnableDnsHostnames: !FindInMap [Values, Config, VPCB_EnableDnsHostnames]
      InstanceTenancy: !FindInMap [Values, Config, DefaultTenancy]
      Tags:
        - Key: Name
          Value: !FindInMap [Values, Config, VPCBName]
